"""Reinicio migraciones

Revision ID: 0375558ab5d2
Revises: 47ecc847a64f
Create Date: 2026-01-13 11:20:41.073634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0375558ab5d2'
down_revision = '47ecc847a64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idPais', sa.String(length=2), nullable=True),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('idTipoReclamo', sa.Integer(), nullable=True),
    sa.Column('idProductoCliente', sa.Integer(), nullable=True),
    sa.Column('obsAlta', sa.Text(), nullable=True),
    sa.Column('fechaAlta', sa.Date(), nullable=True),
    sa.Column('altaPor', sa.String(length=32), nullable=True),
    sa.Column('fechaSolucion', sa.Date(), nullable=True),
    sa.Column('solucionPor', sa.String(length=32), nullable=True),
    sa.Column('idTipoSolucion', sa.Integer(), nullable=True),
    sa.Column('obsSolucion', sa.Text(), nullable=True),
    sa.Column('proximoAviso', sa.Date(), nullable=True),
    sa.Column('pospuestoPor', sa.String(length=32), nullable=True),
    sa.Column('idPrioridad', sa.Integer(), nullable=True),
    sa.Column('reclamadoPor', sa.String(length=32), nullable=True),
    sa.Column('idHoras', sa.Integer(), nullable=True),
    sa.Column('idMinutos', sa.Integer(), nullable=True),
    sa.Column('emailAviso', sa.String(length=256), nullable=True),
    sa.Column('telefonoAviso', sa.String(length=256), nullable=True),
    sa.Column('celularAviso', sa.String(length=256), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclamo_accion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idReclamo', sa.Integer(), nullable=True),
    sa.Column('fechaAccion', sa.Date(), nullable=True),
    sa.Column('accionPor', sa.String(length=32), nullable=True),
    sa.Column('idTipoReclamo', sa.Integer(), nullable=True),
    sa.Column('idTipoAccion', sa.Integer(), nullable=True),
    sa.Column('obsAccion', sa.Text(), nullable=True),
    sa.Column('idHoras', sa.Integer(), nullable=True),
    sa.Column('idMinutos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclamo_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclamo_minutos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_accion_reclamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idTipoReclamo', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('idGRPorigen', sa.Integer(), nullable=True),
    sa.Column('idGRPdestino', sa.Integer(), nullable=True),
    sa.Column('aviso', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('mailFrom', sa.String(length=256), nullable=True),
    sa.Column('mailTo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_reclamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('idGRPorigen', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('postBaja', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_reclamo')
    op.drop_table('tipo_accion_reclamo')
    op.drop_table('reclamo_minutos')
    op.drop_table('reclamo_horas')
    op.drop_table('reclamo_accion')
    op.drop_table('reclamo')
    # ### end Alembic commands ###
