"""Migración inicial limpia

Revision ID: 0a3fbf7b7283
Revises: 
Create Date: 2025-11-11 10:57:44.858333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3fbf7b7283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_id', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_id', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
