"""Reinicio migraciones

Revision ID: 1558f8294bf7
Revises: ed775dec388b
Create Date: 2026-02-04 09:26:57.318127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1558f8294bf7'
down_revision = 'ed775dec388b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra1', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.drop_column('extra1')

    # ### end Alembic commands ###
