"""Reinicio migraciones

Revision ID: 15d513ddb2f2
Revises: aaabc97fbf11
Create Date: 2026-02-06 14:37:17.981008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d513ddb2f2'
down_revision = 'aaabc97fbf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contratos', sa.Boolean(), nullable=True))

    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contratos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('contratos')
        batch_op.drop_column('archivos')

    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('contratos')
        batch_op.drop_column('archivos')

    # ### end Alembic commands ###
