"""Reinicio migraciones

Revision ID: 17525eac8c1f
Revises: 2cbe02583364
Create Date: 2025-12-08 11:41:09.954838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17525eac8c1f'
down_revision = '2cbe02583364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo_familia',
    sa.Column('idEquipoFamilia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=512), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idEquipoFamilia')
    )
    op.create_table('equipo_tipo',
    sa.Column('idTipoEquipo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=512), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('idEquipoFamilia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idTipoEquipo', 'idEquipoFamilia')
    )
    op.create_table('proveedor',
    sa.Column('idProveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proveedor', sa.String(length=512), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('fechaalta', sa.DateTime(), nullable=True),
    sa.Column('altapor', sa.String(length=128), nullable=True),
    sa.Column('fechamodificado', sa.DateTime(), nullable=True),
    sa.Column('modificadopor', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('idProveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    op.drop_table('equipo_tipo')
    op.drop_table('equipo_familia')
    # ### end Alembic commands ###
