"""agregar columna edad a cliente

Revision ID: 1a139c8a5748
Revises: 84f8d745c8ca
Create Date: 2025-11-12 11:46:49.946586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a139c8a5748'
down_revision = '84f8d745c8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
