"""Reinicio migraciones

Revision ID: 25837a2e567e
Revises: cef948cce220
Create Date: 2025-11-21 12:54:22.620997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25837a2e567e'
down_revision = 'cef948cce220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('fechanotificado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notifica', sa.Boolean(), nullable=True))

    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('fechanotificado', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notifica', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('notifica')
        batch_op.drop_column('fechanotificado')
        batch_op.drop_column('uri')

    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('notifica')
        batch_op.drop_column('fechanotificado')
        batch_op.drop_column('uri')

    # ### end Alembic commands ###
