"""Reinicio migraciones

Revision ID: 27900e2085d8
Revises: b90943478c6f
Create Date: 2025-11-19 10:49:22.198014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27900e2085d8'
down_revision = 'b90943478c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechainicio', sa.Date(), nullable=True))
        batch_op.alter_column('fechafin',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.alter_column('fechafin',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('fechainicio')

    # ### end Alembic commands ###
