"""Reinicio migraciones

Revision ID: 2c6eebe238df
Revises: 1558f8294bf7
Create Date: 2026-02-05 10:58:43.638463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c6eebe238df'
down_revision = '1558f8294bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_field_extra_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('idField', sa.Integer(), nullable=True),
    sa.Column('idFieldValue', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.drop_column('extra')
        batch_op.drop_column('extra1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra1', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('extra', mysql.TEXT(), nullable=True))

    op.drop_table('product_field_extra_value')
    # ### end Alembic commands ###
