"""Reinicio migraciones

Revision ID: 2cbe02583364
Revises: c3efe17f90c6
Create Date: 2025-12-04 09:18:35.569823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbe02583364'
down_revision = 'c3efe17f90c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idcliente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hora_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_fin', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_column('hora_fin')
        batch_op.drop_column('hora_inicio')
        batch_op.drop_column('idcliente')

    # ### end Alembic commands ###
