"""Reinicio migraciones

Revision ID: 3027949849c6
Revises: 5fae934e3f4d
Create Date: 2025-11-21 10:25:34.105866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3027949849c6'
down_revision = '5fae934e3f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo_oportunidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idoportunidad', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('fechaalta', sa.DateTime(), nullable=True),
    sa.Column('altapor', sa.LargeBinary(length=16777216), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivo_oportunidad')
    # ### end Alembic commands ###
