"""Reinicio migraciones

Revision ID: 3236ca7c18aa
Revises: bc6543f2f69a
Create Date: 2026-02-11 09:56:21.722214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3236ca7c18aa'
down_revision = 'bc6543f2f69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###
