"""Reinicio migraciones

Revision ID: 35ab44bf4bed
Revises: 3236ca7c18aa
Create Date: 2026-02-11 10:47:15.659869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ab44bf4bed'
down_revision = '3236ca7c18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
