"""Reinicio migraciones

Revision ID: 385fdaa46078
Revises: 4d2815a231cc
Create Date: 2026-01-05 14:34:22.088708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385fdaa46078'
down_revision = '4d2815a231cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_product_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProductClient', sa.Integer(), nullable=True))
        batch_op.drop_column('idContract')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_product_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idContract', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('idProductClient')

    # ### end Alembic commands ###
