"""agregar columna edad a cliente

Revision ID: 40d1cba1a7cb
Revises: 1a139c8a5748
Create Date: 2025-11-12 14:34:42.881822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d1cba1a7cb'
down_revision = '1a139c8a5748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_address'))
        batch_op.drop_index(batch_op.f('ix_users_apartment'))
        batch_op.drop_index(batch_op.f('ix_users_cellphonenumber'))
        batch_op.drop_index(batch_op.f('ix_users_doornumber'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_phonenumber'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phonenumber'), ['phonenumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_doornumber'), ['doornumber'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_cellphonenumber'), ['cellphonenumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_apartment'), ['apartment'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_address'), ['address'], unique=False)

    # ### end Alembic commands ###
