"""Reinicio migraciones

Revision ID: 41c2f0db12fa
Revises: d9190362a844
Create Date: 2026-01-08 15:56:12.318796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c2f0db12fa'
down_revision = 'd9190362a844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursal',
    sa.Column('idPais', sa.String(length=2), nullable=False),
    sa.Column('idSucursal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('idPais', 'idSucursal')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sucursal')
    # ### end Alembic commands ###
