"""Reinicio migraciones

Revision ID: 44375b8872d7
Revises: ca4949059c61
Create Date: 2025-11-17 12:30:46.512573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44375b8872d7'
down_revision = 'ca4949059c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricefilter', mysql.BIT(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('pricefilter')

    # ### end Alembic commands ###
