"""Reinicio migraciones

Revision ID: 4588d8e6d62e
Revises: d662a7847ac2
Create Date: 2025-11-19 11:26:56.509432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4588d8e6d62e'
down_revision = 'd662a7847ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=256), nullable=True))
        batch_op.drop_column('estadoactual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estadoactual', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
