"""Reinicio migraciones

Revision ID: 4654c64978a7
Revises: 71ee3aea8840
Create Date: 2025-12-19 12:49:14.669020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4654c64978a7'
down_revision = '71ee3aea8840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idproduct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('idmoneda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('idperiodo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('importe', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('identificador', sa.Text(), nullable=True))
        batch_op.drop_column('idproducto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idproducto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('identificador')
        batch_op.drop_column('importe')
        batch_op.drop_column('idperiodo')
        batch_op.drop_column('idmoneda')
        batch_op.drop_column('idproduct')

    # ### end Alembic commands ###
