"""Reinicio migraciones

Revision ID: 476b1dd29c4f
Revises: 6c7e32e88adc
Create Date: 2026-02-09 11:43:08.356165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476b1dd29c4f'
down_revision = '6c7e32e88adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FechaNacimiento', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('FechaNacimiento')

    # ### end Alembic commands ###
