"""Reinicio migraciones

Revision ID: 47ecc847a64f
Revises: 41c2f0db12fa
Create Date: 2026-01-12 15:09:02.354603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ecc847a64f'
down_revision = '41c2f0db12fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
