"""Reinicio migraciones

Revision ID: 4965a03b4f55
Revises: 8ead8c38bfbf
Create Date: 2026-02-10 11:19:46.772207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4965a03b4f55'
down_revision = '8ead8c38bfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
