"""Reinicio migraciones

Revision ID: 4ca70f81e386
Revises: bb61f5c68c59
Create Date: 2026-01-19 15:41:02.160356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca70f81e386'
down_revision = 'bb61f5c68c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_solucion_reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idTipoReclamo', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_solucion_reclamo', schema=None) as batch_op:
        batch_op.drop_column('idTipoReclamo')

    # ### end Alembic commands ###
