"""Reinicio migraciones

Revision ID: 4cea8f21cac0
Revises: e596d9157739
Create Date: 2025-11-19 14:42:27.702180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cea8f21cac0'
down_revision = 'e596d9157739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaalta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('altapor', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('altapor')
        batch_op.drop_column('fechaalta')

    # ### end Alembic commands ###
