"""Reinicio migraciones

Revision ID: 4d2815a231cc
Revises: d06340a7cc50
Create Date: 2026-01-05 11:17:20.283544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2815a231cc'
down_revision = 'd06340a7cc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
