"""Reinicio migraciones

Revision ID: 4e0b0e9c8347
Revises: a579b1cfd9c0
Create Date: 2026-01-13 14:42:41.727088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0b0e9c8347'
down_revision = 'a579b1cfd9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prioridades')
    # ### end Alembic commands ###
