"""Reinicio migraciones

Revision ID: 501f5da6f291
Revises: ec7758099b42
Create Date: 2025-12-01 16:18:34.009608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501f5da6f291'
down_revision = 'ec7758099b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalid', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('externalid')

    # ### end Alembic commands ###
