"""Reinicio migraciones

Revision ID: 55432726d60a
Revises: 8801719737a4
Create Date: 2025-12-11 11:31:56.701012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55432726d60a'
down_revision = '8801719737a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirige', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('uriredireccion', sa.String(length=4096), nullable=True))

    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirige', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('uriredireccion', sa.String(length=4096), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('uriredireccion')
        batch_op.drop_column('redirige')

    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('uriredireccion')
        batch_op.drop_column('redirige')

    # ### end Alembic commands ###
