"""Reinicio migraciones

Revision ID: 5d26fca4c341
Revises: ed9c38fac509
Create Date: 2025-11-13 15:20:02.757555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d26fca4c341'
down_revision = 'ed9c38fac509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('descripcion')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
