"""Reinicio migraciones

Revision ID: 5f2bfe5b7535
Revises: 44375b8872d7
Create Date: 2025-11-17 13:23:07.006768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2bfe5b7535'
down_revision = '44375b8872d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filterby', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('filterby')

    # ### end Alembic commands ###
