"""Reinicio migraciones

Revision ID: 5fae934e3f4d
Revises: 
Create Date: 2025-11-20 11:46:08.091058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fae934e3f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contract', ['idcontract'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
