"""Reinicio migraciones

Revision ID: 600d0fa8cfb2
Revises: 2c6eebe238df
Create Date: 2026-02-05 15:17:03.106944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600d0fa8cfb2'
down_revision = '2c6eebe238df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Manzana', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Solar', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('Solar')
        batch_op.drop_column('Manzana')

    # ### end Alembic commands ###
