"""Reinicio migraciones

Revision ID: 670ba1dbb633
Revises: 25837a2e567e
Create Date: 2025-11-21 13:26:41.980596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670ba1dbb633'
down_revision = '25837a2e567e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automatica', sa.Boolean(), nullable=True))

    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automatica', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('automatica')

    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('automatica')

    # ### end Alembic commands ###
