"""Reinicio migraciones

Revision ID: 6c7e32e88adc
Revises: 15d513ddb2f2
Create Date: 2026-02-09 10:36:13.987686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7e32e88adc'
down_revision = '15d513ddb2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internalname', sa.String(length=32), nullable=True))

    with op.batch_alter_table('product_field_extra_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internalname', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_extra_value', schema=None) as batch_op:
        batch_op.drop_column('internalname')

    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('internalname')

    # ### end Alembic commands ###
