"""Reinicio migraciones

Revision ID: 71ee3aea8840
Revises: d9217a857782
Create Date: 2025-12-18 16:26:34.617880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71ee3aea8840'
down_revision = 'd9217a857782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idProductContract', sa.Integer(), nullable=True))
        batch_op.drop_column('idContract')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idContract', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('idProductContract')

    # ### end Alembic commands ###
