"""Reinicio migraciones

Revision ID: 726cd733f185
Revises: 4965a03b4f55
Create Date: 2026-02-10 12:30:41.184766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726cd733f185'
down_revision = '4965a03b4f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalid', sa.String(length=256), nullable=True))

    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('externalid', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.drop_column('externalid')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('externalid')

    # ### end Alembic commands ###
