"""Reinicio migraciones

Revision ID: 72cad0822ba4
Revises: 4ca70f81e386
Create Date: 2026-01-20 16:17:33.087169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cad0822ba4'
down_revision = '4ca70f81e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.alter_column('fechaAlta',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('fechaSolucion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('proximoAviso',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('reclamo_accion', schema=None) as batch_op:
        batch_op.alter_column('fechaAccion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo_accion', schema=None) as batch_op:
        batch_op.alter_column('fechaAccion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.alter_column('proximoAviso',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('fechaSolucion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('fechaAlta',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
