"""Reinicio migraciones

Revision ID: 7db4be5b2f62
Revises: b195720d079c
Create Date: 2025-11-21 11:27:12.209274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7db4be5b2f62'
down_revision = 'b195720d079c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoarchivo', sa.Integer(), nullable=True))
        batch_op.alter_column('archivo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.drop_column('idtipoarchivo')

    # ### end Alembic commands ###
