"""agregar columna edad a cliente

Revision ID: 84649ec75ab6
Revises: b497865c9b4e
Create Date: 2025-11-13 12:44:04.323979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84649ec75ab6'
down_revision = 'b497865c9b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_oportunidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idoportunidad', sa.Integer(), nullable=True),
    sa.Column('idtipoportunidad', sa.Integer(), nullable=True),
    sa.Column('idetapaoportunidad', sa.Integer(), nullable=True),
    sa.Column('fechaalta', sa.DateTime(), nullable=True),
    sa.Column('fecharealizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoportunidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notificar', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('icono', sa.String(length=256), nullable=True))
        batch_op.drop_column('idoportunidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idoportunidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('icono')
        batch_op.drop_column('notificar')
        batch_op.drop_column('idtipoportunidad')

    op.drop_table('estado_oportunidad')
    # ### end Alembic commands ###
