"""Reinicio migraciones

Revision ID: 8469f0ab732b
Revises: c467bd84a48a
Create Date: 2025-12-16 11:30:08.473305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8469f0ab732b'
down_revision = 'c467bd84a48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaadquisicion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('fechaadquisicion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaadquisicion', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('fechaadquisicion')

    # ### end Alembic commands ###
