"""agregar columna edad a cliente

Revision ID: 84f8d745c8ca
Revises: fa29595e260d
Create Date: 2025-11-11 15:41:51.388600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f8d745c8ca'
down_revision = 'fa29595e260d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idGrupoVendedor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contacto', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('celular', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('cedula', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('agente', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('interno', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.drop_column('interno')
        batch_op.drop_column('agente')
        batch_op.drop_column('cedula')
        batch_op.drop_column('celular')
        batch_op.drop_column('telefono')
        batch_op.drop_column('contacto')
        batch_op.drop_column('idGrupoVendedor')

    # ### end Alembic commands ###
