"""Reinicio migraciones

Revision ID: 8801719737a4
Revises: f25edad08cd4
Create Date: 2025-12-09 12:55:01.668536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8801719737a4'
down_revision = 'f25edad08cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoagenda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('notas')
        batch_op.drop_column('idtipoagenda')

    # ### end Alembic commands ###
