"""Reinicio migraciones

Revision ID: 8e98d6ce1ae8
Revises: ff6f3583e10e
Create Date: 2025-11-27 14:56:21.225078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e98d6ce1ae8'
down_revision = 'ff6f3583e10e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plazo',
    sa.Column('idPlazo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idPlazo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plazo')
    # ### end Alembic commands ###
