"""Reinicio migraciones

Revision ID: 92d820ef8887
Revises: 3027949849c6
Create Date: 2025-11-21 10:48:56.733306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92d820ef8887'
down_revision = '3027949849c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo', sa.LargeBinary(length=16777216), nullable=True))
        batch_op.alter_column('altapor',
               existing_type=mysql.LONGBLOB(),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.alter_column('altapor',
               existing_type=sa.String(length=256),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.drop_column('archivo')

    # ### end Alembic commands ###
