"""Reinicio migraciones

Revision ID: 9509bd1b739d
Revises: 17b2f5d0ba9d
Create Date: 2025-12-30 15:11:54.832910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9509bd1b739d'
down_revision = '17b2f5d0ba9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechainicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fechafin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.drop_column('fechafin')
        batch_op.drop_column('fechainicio')

    # ### end Alembic commands ###
