"""Reinicio migraciones

Revision ID: 96db4e0c6b01
Revises: bce4a4857678
Create Date: 2025-12-17 15:32:18.876080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96db4e0c6b01'
down_revision = 'bce4a4857678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaasignado', sa.DateTime(), nullable=True))
        batch_op.drop_column('fechasignado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechasignado', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('fechaasignado')

    # ### end Alembic commands ###
