"""Reinicio migraciones

Revision ID: 99858e068584
Revises: f1dfefaa4d41
Create Date: 2026-01-21 15:45:29.149325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99858e068584'
down_revision = 'f1dfefaa4d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo_archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idreclamo', sa.Integer(), nullable=True))
        batch_op.drop_column('idoportunidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo_archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idoportunidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('idreclamo')

    # ### end Alembic commands ###
