"""Reinicio migraciones

Revision ID: a579b1cfd9c0
Revises: 0375558ab5d2
Create Date: 2026-01-13 14:30:13.267688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a579b1cfd9c0'
down_revision = '0375558ab5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_reclamo', schema=None) as batch_op:
        batch_op.drop_column('identificador')

    # ### end Alembic commands ###
