"""Reinicio migraciones

Revision ID: aaabc97fbf11
Revises: 600d0fa8cfb2
Create Date: 2026-02-05 15:44:34.510233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaabc97fbf11'
down_revision = '600d0fa8cfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Padron', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('Padron')

    # ### end Alembic commands ###
