"""Reinicio migraciones

Revision ID: b195720d079c
Revises: 92d820ef8887
Create Date: 2025-11-21 11:20:07.663629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b195720d079c'
down_revision = '92d820ef8887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_archivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=True),
    sa.Column('abreviacion', sa.String(length=256), nullable=True),
    sa.Column('idexterno', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(length=16777216),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo_oportunidad', schema=None) as batch_op:
        batch_op.alter_column('archivo',
               existing_type=sa.LargeBinary(length=16777216),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    op.drop_table('tipo_archivo')
    # ### end Alembic commands ###
