"""Reinicio migraciones

Revision ID: b281f278bc00
Revises: bdf916f65b35
Create Date: 2026-02-03 10:44:36.409669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b281f278bc00'
down_revision = 'bdf916f65b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipooportunidad', sa.Integer(), nullable=True))
        batch_op.drop_column('idtipoportunidad')

    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipooportunidad', sa.Integer(), nullable=True))
        batch_op.drop_column('idtipoportunidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapa_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoportunidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('idtipooportunidad')

    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoportunidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('idtipooportunidad')

    # ### end Alembic commands ###
