"""agregar columna edad a cliente

Revision ID: b497865c9b4e
Revises: 40d1cba1a7cb
Create Date: 2025-11-12 14:56:16.827151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b497865c9b4e'
down_revision = '40d1cba1a7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
