"""Reinicio migraciones

Revision ID: b90943478c6f
Revises: 5f2bfe5b7535
Create Date: 2025-11-18 11:56:38.641608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b90943478c6f'
down_revision = '5f2bfe5b7535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idoportunidad', sa.Integer(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('cliente')
        batch_op.drop_column('importe')
        batch_op.drop_column('idperiodo')
        batch_op.drop_column('lenguaje')
        batch_op.drop_column('idcliente')
        batch_op.drop_column('idmoneda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idmoneda', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idcliente', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lenguaje', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('idperiodo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('importe', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('cliente', mysql.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('idoportunidad')

    # ### end Alembic commands ###
