"""Reinicio migraciones

Revision ID: bb61f5c68c59
Revises: 4e0b0e9c8347
Create Date: 2026-01-19 15:26:28.910958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb61f5c68c59'
down_revision = '4e0b0e9c8347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_solucion_reclamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificador', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_solucion_reclamo')
    # ### end Alembic commands ###
