"""Reinicio migraciones

Revision ID: bc6543f2f69a
Revises: 726cd733f185
Create Date: 2026-02-11 09:47:06.699087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6543f2f69a'
down_revision = '726cd733f185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###
