"""Reinicio migraciones

Revision ID: bdf916f65b35
Revises: d782c2eabcea
Create Date: 2026-01-26 16:43:30.071114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf916f65b35'
down_revision = 'd782c2eabcea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altapor', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.drop_column('altapor')

    # ### end Alembic commands ###
