"""Reinicio migraciones

Revision ID: c3efe17f90c6
Revises: 501f5da6f291
Create Date: 2025-12-03 11:54:56.387081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3efe17f90c6'
down_revision = '501f5da6f291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=32), nullable=True),
    sa.Column('idoportunidad', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('fechacancelado', sa.Date(), nullable=True),
    sa.Column('fechacompletado', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_agenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_agenda')
    op.drop_table('agenda')
    # ### end Alembic commands ###
