"""Reinicio migraciones

Revision ID: c467bd84a48a
Revises: 55432726d60a
Create Date: 2025-12-16 11:09:23.555217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c467bd84a48a'
down_revision = '55432726d60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fechaadquisicion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('fechaadquisicion')

    # ### end Alembic commands ###
