"""Reinicio migraciones

Revision ID: ca4949059c61
Revises: cf027f382bc4
Create Date: 2025-11-17 12:21:47.721521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca4949059c61'
down_revision = 'cf027f382bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_field_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('idField', sa.Integer(), nullable=True),
    sa.Column('visible', mysql.BIT(length=1), nullable=True),
    sa.Column('idmoneda', sa.Integer(), nullable=True),
    sa.Column('importe', sa.Double(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importe', sa.Double(), nullable=True))
        batch_op.drop_column('monto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', mysql.DOUBLE(asdecimal=True), nullable=True))
        batch_op.drop_column('importe')

    op.drop_table('product_field_price')
    # ### end Alembic commands ###
