"""Reinicio migraciones

Revision ID: cef948cce220
Revises: 22c76de85d8b
Create Date: 2025-11-21 12:28:29.483448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef948cce220'
down_revision = '22c76de85d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_archivo', schema=None) as batch_op:
        batch_op.drop_column('visible')

    # ### end Alembic commands ###
