"""Reinicio migraciones

Revision ID: cf027f382bc4
Revises: 5d26fca4c341
Create Date: 2025-11-17 12:04:02.848651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf027f382bc4'
down_revision = '5d26fca4c341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
