"""Reinicio migraciones

Revision ID: d06340a7cc50
Revises: 9509bd1b739d
Create Date: 2025-12-30 15:13:07.177353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06340a7cc50'
down_revision = '9509bd1b739d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altapor', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_client', schema=None) as batch_op:
        batch_op.drop_column('altapor')

    # ### end Alembic commands ###
