"""Reinicio migraciones

Revision ID: d662a7847ac2
Revises: 27900e2085d8
Create Date: 2025-11-19 11:19:10.712773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd662a7847ac2'
down_revision = '27900e2085d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estadoactual', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oportunidad', schema=None) as batch_op:
        batch_op.drop_column('estadoactual')

    # ### end Alembic commands ###
