"""Reinicio migraciones

Revision ID: d782c2eabcea
Revises: 99858e068584
Create Date: 2026-01-23 11:23:11.993485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd782c2eabcea'
down_revision = '99858e068584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sector', ['sector_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sector_id')

    # ### end Alembic commands ###
