"""Reinicio migraciones

Revision ID: d9217a857782
Revises: 96db4e0c6b01
Create Date: 2025-12-18 10:31:04.305535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9217a857782'
down_revision = '96db4e0c6b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEquipo', sa.Integer(), nullable=True),
    sa.Column('idContract', sa.Integer(), nullable=True),
    sa.Column('idOportunidad', sa.Integer(), nullable=True),
    sa.Column('fechaalta', sa.DateTime(), nullable=True),
    sa.Column('altapor', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idclient', sa.Integer(), nullable=False),
    sa.Column('idproducto', sa.Integer(), nullable=False),
    sa.Column('idequipo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'idclient', 'idproducto', 'idequipo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_equipment')
    op.drop_table('equipo_contract')
    # ### end Alembic commands ###
