"""Reinicio migraciones

Revision ID: d98508777363
Revises: b281f278bc00
Create Date: 2026-02-03 11:23:27.271965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98508777363'
down_revision = 'b281f278bc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field_value', schema=None) as batch_op:
        batch_op.drop_column('extra')

    # ### end Alembic commands ###
