"""Reinicio migraciones

Revision ID: e596d9157739
Revises: 4588d8e6d62e
Create Date: 2025-11-19 12:38:31.738966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e596d9157739'
down_revision = '4588d8e6d62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_accion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('responsable', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accion_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idtipoaccion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accion_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('idtipoaccion')

    op.drop_table('tipo_accion')
    # ### end Alembic commands ###
