"""Reinicio migraciones

Revision ID: ec7758099b42
Revises: 8e98d6ce1ae8
Create Date: 2025-11-27 15:51:18.125538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec7758099b42'
down_revision = '8e98d6ce1ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identificador', sa.Text(), nullable=True))

    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', mysql.BIT(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('identifier')

    with op.batch_alter_table('product_contract', schema=None) as batch_op:
        batch_op.drop_column('identificador')

    # ### end Alembic commands ###
