"""Reinicio migraciones

Revision ID: ed775dec388b
Revises: d98508777363
Create Date: 2026-02-03 15:11:58.312801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed775dec388b'
down_revision = 'd98508777363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_field_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idField', sa.Integer(), nullable=True),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('fechaasignado', sa.Date(), nullable=True),
    sa.Column('asignadopor', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automatic', mysql.BIT(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_field', schema=None) as batch_op:
        batch_op.drop_column('automatic')

    op.drop_table('product_field_values')
    # ### end Alembic commands ###
