"""Reinicio migraciones

Revision ID: ed9c38fac509
Revises: 84649ec75ab6
Create Date: 2025-11-13 14:52:24.010643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9c38fac509'
down_revision = '84649ec75ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predecesor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notificar', sa.String(length=4096), nullable=True))
        batch_op.add_column(sa.Column('sectorresponsable', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('icono', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_oportunidad', schema=None) as batch_op:
        batch_op.drop_column('icono')
        batch_op.drop_column('sectorresponsable')
        batch_op.drop_column('notificar')
        batch_op.drop_column('predecesor')

    # ### end Alembic commands ###
