"""Reinicio migraciones

Revision ID: f1dfefaa4d41
Revises: 72cad0822ba4
Create Date: 2026-01-21 15:08:42.027706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1dfefaa4d41'
down_revision = '72cad0822ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamo_archivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idoportunidad', sa.Integer(), nullable=True),
    sa.Column('idtipoarchivo', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('fechaalta', sa.DateTime(), nullable=True),
    sa.Column('altapor', sa.String(length=256), nullable=True),
    sa.Column('archivo', mysql.LONGBLOB(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reclamo_archivo')
    # ### end Alembic commands ###
