"""Reinicio migraciones

Revision ID: f25edad08cd4
Revises: 17525eac8c1f
Create Date: 2025-12-08 15:46:58.062309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25edad08cd4'
down_revision = '17525eac8c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idfamilia', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('idfamilia')

    # ### end Alembic commands ###
