"""agregar columna edad a cliente

Revision ID: fa29595e260d
Revises: 0a3fbf7b7283
Create Date: 2025-11-11 15:25:47.674574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa29595e260d'
down_revision = '0a3fbf7b7283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor',
    sa.Column('idVendedor', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idVendedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedor')
    # ### end Alembic commands ###
