"""Reinicio migraciones

Revision ID: ff6f3583e10e
Revises: 670ba1dbb633
Create Date: 2025-11-27 14:39:27.443749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6f3583e10e'
down_revision = '670ba1dbb633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneda',
    sa.Column('idMoneda', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=32), nullable=True),
    sa.Column('abreviacion', sa.String(length=32), nullable=True),
    sa.Column('idExterno', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idMoneda')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneda')
    # ### end Alembic commands ###
