from app import db

class Equipo(db.Model):
    idequipo = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idtipoequipo = db.Column(db.Integer)
    idmarca = db.Column(db.Integer)
    idmodelo = db.Column(db.Integer)
    idproveedor = db.Column(db.Integer)
    fechaalta = db.Column(db.DateTime)
    altapor = db.Column(db.String(128))
    fechabaja = db.Column(db.DateTime)
    bajapor  = db.Column(db.String(128))
    nroserie = db.Column(db.String(2056), unique=False)
    fechasignado = db.Column(db.DateTime)
    asignadopor = db.Column(db.String(128))
    idcliente = db.Column(db.Integer)
    observacion = db.Column(db.Text)

class Marca(db.Model):
    idMarca = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idtipoequipo = db.Column(db.Integer)
    marca = db.Column(db.String(512))
    visible = db.Column(db.Boolean)
    fechaalta = db.Column(db.DateTime)
    altapor =  db.Column(db.String(128))
    fechamodificado = db.Column(db.DateTime)
    modificadopor = db.Column(db.String(128))
    idgarantia = db.Column(db.Integer)
    observacion = db.Column(db.Text)

class Modelo(db.Model):
    idmodelo = db.Column(db.Integer, primary_key=True, autoincrement=True)
    idMarca = db.Column(db.Integer)
    idtipoequipo = db.Column(db.Integer)
    modelo = db.Column(db.String(512))
    visible = db.Column(db.Boolean)
    fechaalta = db.Column(db.DateTime)
    altapor =  db.Column(db.String(128))
    fechamodificado = db.Column(db.DateTime)
    modificadopor = db.Column(db.String(128))
    idgarantia = db.Column(db.Integer)
    observacion = db.Column(db.Text)
    idmoneda = db.Column(db.Integer)
    precio = db.Column(db.DECIMAL(10, 2))
    idmonedacompra = db.Column(db.Integer)
    precioCompra = db.Column(db.DECIMAL(10, 2))

class Proveedor():
    idProveedor = db.Column(db.Integer, primary_key=True, autoincrement=True)
    proveedor = db.Column(db.String(512))
    observacion = db.Column(db.Text)
    visible = db.Column(db.Boolean)
    fechaalta = db.Column(db.DateTime)
    altapor =  db.Column(db.String(128))
    fechamodificado = db.Column(db.DateTime)
    modificadopor = db.Column(db.String(128))